language: objective-c
osx_image: xcode9.2

before_install:
    - pod repo update

script:
    - xcodebuild clean build test -sdk iphonesimulator -workspace AirQualityMonitor.xcworkspace -scheme AirQualityMonitor CODE_SIGNING_REQUIRED=NO
