language: objective-c
osx_image: xcode9.2

before_install:
    - pod repo update

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace AirQualityMonitor.xcworkspace -scheme AirQualityMonitorTests CODE_SIGNING_REQUIRED=NO
