language: objective-c
osx_image: xcode9.2

before_install:
    - pod repo update

script:
    - travis_wait xcodebuild clean build -sdk iphonesimulator -workspace AirQualityMonitor.xcworkspace -scheme AirQualityMonitor CODE_SIGNING_REQUIRED=NO
    - xcodebuild test -sdk iphonesimulator -workspace AirQualityMonitor.xcworkspace -scheme AirQualityMonitor CODE_SIGNING_REQUIRED=NO
